### ISSUE TITLE
buildem broke gdb on fedora

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/buildem#33]
gdb returns the following error

```
gdb: symbol lookup error: gdb: undefined symbol: PyUnicodeUCS4_FromEncodedObject
```

after buildem/lib added to the LD_LIBRARY_PATH. The problem might be related to incompatible python build in buildem.

**Comment by stuarteberg** [comment]
>The problem might be related to incompatible python build in buildem.

Right.  The issue is that `gdb` is linked against your system's version of `libpython.so`, but you have activated buildem's version python, which isn't identical.

Here's how to fix it:

http://stackoverflow.com/questions/20951429/how-do-i-use-gdb-when-im-using-a-debug-version-of-python

Since this is likely to come up again, I've just added a [note about this issue to the BuildEM readme](https://github.com/janelia-flyem/buildem/#using-gdb).
